# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import df_pb2 as df__pb2


class dataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.read_data = channel.unary_unary(
        '/data/read_data',
        request_serializer=df__pb2.Path.SerializeToString,
        response_deserializer=df__pb2.Path.FromString,
        )


class dataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def read_data(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_dataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'read_data': grpc.unary_unary_rpc_method_handler(
          servicer.read_data,
          request_deserializer=df__pb2.Path.FromString,
          response_serializer=df__pb2.Path.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'data', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
